# Some configs to make sure dass can work well.
lang = "zh-simplified"         # Your work language. It's now support `zh-simplified` and `en`

[llm]
provider = "Antropic"          # OpenAI, Qwen, Anthropic, Deepseek, Google, OpenRouter
api_key = "xx"                 # Your API KEY
base_url = "xx"                # Base url
model = "Claude-4 sonnet"      # model name which one you select

[qdrant]
host = "localhost"             # your qdrant host, default to `localhost`
port = 6333                    # use your qdrant port, default to 6333
dim = 1024                     # dim of embedding information default to 1024. If you don't know the concept of embedding dim just default is fine.
distance_type = "cosine"       # distance type default to cosine. If you don't know the concept of embedding search. Default is the best.